### ISSUE TITLE
Can not access file system with new sdk versions

### ISSUE THREAD

**Issue by ThomasWerthenbach** [Tribler/trustchain-superapp#90]

**Comment by synctext** [comment]
Could you please post the exact error or more detailed please?

**Comment by brian2509** [comment]
Could be a possible fix for your problem: https://github.com/Tribler/trustchain-superapp/pull/91

**Comment by rmadhwal** [comment]
Hi, the error we see is the below:
```
Suppressed: java.io.IOException: No original dex files found for dex location (x86) /storage/emulated/0/Download/act.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:367)
        at dalvik.system.DexFile.<init>(DexFile.java:109)
```
This can be replicated by trying to execute any apk inside the freedom-of-computing app.

We believe that the issue is caused by the [storage updates in Android 11](https://developer.android.com/about/versions/11/privacy/storage)

Currently, `requestLegacyExternalStorage` is set in the app's manifest however, starting SDK Version 30 this flag seems to be ignored in Android 11. Hence, if we are required to upgrade the SDK it seems like the right direction for us to look at would be to either use scoped storage and require users to use the application's data directories or to use `ACTION_OPEN_DOCUMENT` and ask the user to provide us permission to use the file.
